### ISSUE TITLE
Spigot workaround for `ChunkProviderServer#getChunkAtIfLoadedImmediately()`

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit-Adapters#5]
Named method in the title is paper only, so using using it on spigot leads to a NoSuchMethodError. We should add some kind of workaround here.

**Comment by MattBDev** [comment]
If we can't come up with a workaround for Spigot another option would be to make whatever relies on this method a Paper exclusive function.

**Comment by NotMyFault** [comment]
I couldn't trigger named exception yet, but we can catch it at least.
