### ISSUE TITLE
Light inconsistency with addons

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit-Adapters#6]
See https://github.com/IntellectualSites/FastAsyncVoxelSniper/pull/37 for the conversation.

**Comment by MattBDev** [comment]
I can confirm this issue on Paper 1.17 (build number unknown). Using a custom build of FAWE from the week of 2021-07-05

**Comment by NotMyFault** [comment]
Cannot replicate anymore, assume it resolved itself with the Tuinity merge into Paper.
